(defn start-ssh-serveo-based-s-md-visible-task [task-port md-file-path sharing-name checking-url-port]
  ;;Should write a bash script to start the ssh serveo based s-md-visible task
  ;;The bash script should do the following steps:
  ;; 1.Start the checking-url server on the checking-url-port to return 200 status code when the markdown content is visible
  ;; 2.Start the s-md-visible task to make the markdown content visible on the task-port
  ;; 3.Start the ssh serveo tunnel to expose the task-port to the public
  ;; 4.start the ssh serveo tunnel to expose the checking-url-port to the public
  ;; 5.Return the public url of the markdown content
  ;; The public url should be in the format: https://<domain>/stateful-md/<sharing-name>
  ;; The public checking url should be in the format: https://<domain>.serveo.net/check-md-visible/<sharing-name>
  ;; The <domain> is generated by serveo
  ;; 6.Show the public url and public checking url to the user, and tell them when you kill the bash script the tunnels will be closed, the markdown content will not be visible anymore
  )

(defn main []
  ;; This is a the prompt of v0.1 version of this project
  ;; The changes and new features will be placed in the changes and features list below;
  ;; The changes are the function name list that exists in v0.0 version, and it desciribes the changes made to these functions;
  ;; The features are the new function name list that added in v0.1 version, but it not exists in v0.0 version, and it describes the new features added to the project;
  (let [changes []
        features [start-ssh-serveo-based-s-md-visible-task]]))
